#ifndef NODEMCUV3_CAPTIVEPORTAL_RESOURCES_H
#define NODEMCUV3_CAPTIVEPORTAL_RESOURCES_H

#endif //NODEMCUV3_CAPTIVEPORTAL_RESOURCES_H

class Resources {
public:
  const String fetchStatusJs {
    "var error = function(message, err) {"
      "console.log(message, err);"
      "var container = document.getElementById('error');"
      "container.innerText = message + \". Caused by: \" + err;"
      "container.style.display = null"
    "};"
    "var fetchStatus = function() {"
      "return fetch('/status', {"
        "method: 'get'"
      "})"
          ".then(function(response) {"
            "if(!response.ok) {"
              "throw new Error('Invalid status code: ' + response.status)"
            "}"
            "return response.json();"
          "})"
          ".catch(function(err) {"
            "console.log(err);"
            "error(\"Fetch template error!\", err);"
            "throw err;"
          "});"
    "};"
  };

  const String header {
    "<!DOCTYPE html>"
    "<html lang=\"en\">"
    "<head>"
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />"
      "<meta charset=\"utf-8\">"
      "<title>ESP8266 Portal</title>"
      "<style>"
        "input {"
          "display: block;"
        "}"
        "input[type=submit] {"
          "display: inline;"
          "margin-right: 3px;"
          "margin-top: 5px;"
        "}"
        ".inline {"
          "display: inline;"
        "}"
        ".data-ssid {"
          "font-weight: bold;"
        "}"
        ".centered {"
          "text-align: center;"
        "}"
        ".hidden {"
          "display: none;"
        "}"
        ".error {"
          "color: red;"
        "}"
        ".loading-text {"
          "color: gray;"
          "font-style: italic;"
        "}"
        ".status-table td:first-child {"
          "text-align: right;"
          "white-space: nowrap;"
        "}"
        ".status-table td:nth-child(2) {"
          "font-weight: bold;"
        "}"
      "</style>"
    "</head>"
    "<body>"
  };

  const String footer {
      "<hr />"
      "<p class=\"centered\"><a href=\"/\">Main page</a></p>"
    "</body>"
    "</html>"
  };
};